/* Day - 2
Code - Lucky Seven

Chef considers the number 77 lucky. As a result, he believes that the 77-th letter he sees on a day is his lucky letter of the day.

You are given a string SS of length 1010, denoting the first 1010 letters Chef saw today.
What is Chef's lucky letter?

Input Format -
The only line of input contains a string SS, of length 1010.

Output Format - 
Print a single character: Chef's lucky letter .
*/

#include <bits/stdc++.h>
using namespace std;

int main() {
	char s[10];
	cin>>s;
	cout<<s[6];
}
